steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [
        'functions',
        'deploy', '$_FUNCTION_NAME',
        '--memory', '256MB',
        '--trigger-event', 'google.storage.object.finalize',
        '--trigger-resource', '$_TRIGGER_BUCKET',
        '--source', '$_SOURCE',
        '--entry-point', 'loadJsonLinesIntoBigQuery',
        '--runtime', 'nodejs10',
        '--max-instances', '$_MAX_INSTANCES',
        '--service-account', '$_SERVICE_ACCOUNT',
        '--set-env-vars', 'TARGET_DATASET=$_TARGET_DATASET,TARGET_TABLE=$_TARGET_TABLE',
      ]
